config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shifts, only: %i[index new create edit]
  resources :roles
  get '/user_roles', to: 'roles#user_roles'
  get '/role_select', to: 'roles#role_select'
  get '/user_select', to: 'shifts#user_select'
  get '/shift_data', to: 'shifts#shift_data'
  root to: 'shifts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/calender.rb
class Calender < ApplicationRecord
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '事業所検診' },
    { id: 3, name: '特定検診' },
    { id: 4, name: '特老' },
    { id: 5, name: 'がん検診' },
    { id: 6, name: '設営' }
  ]
  include ActiveHash::Associations
  has_many :shift
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_role_relations
  has_many :users, through: :user_role_relations

  validates :tag_name, uniqueness: true
end

app/models/shift.rb
class Shift < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  has_many :user_shifts
  has_many :users, through: :user_shifts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_role_relations
  has_many :roles, through: :user_role_relations

  has_many :user_shifts
  has_many :shifts, through: :user_shifts
end

app/models/user_role_relation.rb
class UserRoleRelation < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/user_shift.rb
class UserShift < ApplicationRecord
  belongs_to :user
  belongs_to :shift
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def index; end

  def role_select
    user = User.find(params[:selected_user_id])
    roles = user.roles
    role_select = Role.where.not(id: roles.pluck(:id))
    role_select = role_select.map { |role| [role.id, role.role] }
    render json: role_select
  end

  def user_roles
    user = User.find(params[:selected_user_id])
    roles = user.roles
    roles_html = roles.map { |role| "<div class='role-tag'>#{role.role}</div>" }.join(' ')
    render plain: roles_html
  end

  def create
    @user = User.find(params[:user_id])
    role_ids = params[:role_ids]
    role_ids.each do |role_id|
      if UserRoleRelation.create(user_id: @user.id, role_id: role_id)
      else
        flash.now[:alert] = '役割の更新に失敗しました。'
        render :index
        return
      end
    end
    redirect_to roles_path, notice: '役割が更新されました。'
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  before_action :set_beginning_of_week

  def index
    @dates
  end

  def new
    @shift = Shift.new
    @users_roles = User.includes(:roles)
  end

  def create
    shift_date = params[:shift][:shift_date]
    selected_user_ids = params[:shift][:user_role_combinations]
    @shift = Shift.new(shift_date: shift_date)
    if @shift.save
      selected_user_ids.each do |role_id, user_ids|
        user_ids.each do |user_id|
          user_id[1].each do |user_id|
            UserShift.create(user_id: user_id, role_id: role_id, shift_id: @shift.id)
          end
        end
      end
      redirect_to new_shift_path, notice: '保存しました。'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def shift_data
    user_shift = User.includes(:shift)
    user_role = User.includes(:role)
    render json: { user_shift: user_shift, user_role: user_role }
  end

  private

  def set_beginning_of_week
    Date.beginning_of_week = :sunday
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shifter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "devise/shared/header"%>
    <%= yield %>
  </body>
</html>

app/views/roles/index.html.erb
<div class="edit-title">
  スタッフ編集
</div>
<%= form_with model: @role, url: roles_path, local: true do |f| %>
  <div class="role-category-box">
      <%= f.select :user_id, options_for_select([["編集するスタッフを選択してください", ""]] + User.all.map { |user| [user.name, user.id] }) %>
      <div class="custom-select">
        <select id="role_ids" name="role_ids[]" class = "role_ids" multiple >
      </select>
      </div>
      <%= f.submit "保存する", class: "btn" %>
  </div>
<% end %>

<div id="user-details" class="user-details" style="display: none;">
  <div id="user-name" class="user-name" style="display: none;">
  </div>
  <div id="user-roles" class="user-roles" style="display: none;">
  </div>
</div>

app/views/shifts/_typeA.html.erb
<div>
  所内検診  
</div>
<div class="shift-detail">
  <%= form_with model: shift, url: shifts_path, local: true do |f| %>
  <div class="shift-date">
    <%= f.date_field :shift_date %>
  </div>   
  <div class="roll">
    問診
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[1]{}", options_for_select(User.joins(:roles).where(roles: { id: 1}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    採血
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[2]{}", options_for_select(User.joins(:roles).where(roles: { id: 2}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[14]{}", options_for_select(User.joins(:roles).where(roles: { id: 14}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[3]{}", options_for_select(User.joins(:roles).where(roles: { id: 3}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    肺機能検査
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[15]{}", options_for_select(User.joins(:roles).where(roles: { id: 15}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    腹囲測定
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[4]{}", options_for_select(User.joins(:roles).where(roles: { id: 4}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    聴力検査
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[5]{}", options_for_select(User.joins(:roles).where(roles: { id: 5}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    眼底
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[6]{}", options_for_select(User.joins(:roles).where(roles: { id: 6}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    エコー
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[7]]{}", options_for_select(User.joins(:roles).where(roles: { id: 7}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    胃透視介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[8]{}", options_for_select(User.joins(:roles).where(roles: { id: 8}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    診察介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[10]{}", options_for_select(User.joins(:roles).where(roles: { id: 10}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<%= f.submit "保存する", class: "btn" %>
<% end %>

app/views/shifts/_typeB.html.erb
<div class="shift-detail">
  <div class="roll">
    問診
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[1]{}", options_for_select(User.joins(:roles).where(roles: { id: 1}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    採血
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[2]{}", options_for_select(User.joins(:roles).where(roles: { id: 2}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[14]{}", options_for_select(User.joins(:roles).where(roles: { id: 14}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[3]{}", options_for_select(User.joins(:roles).where(roles: { id: 3}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    腹囲測定
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[4]{}", options_for_select(User.joins(:roles).where(roles: { id: 4}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    聴力検査
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[5]{}", options_for_select(User.joins(:roles).where(roles: { id: 5}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    眼底
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[6]{}", options_for_select(User.joins(:roles).where(roles: { id: 6}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    胃透視介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[8]{}", options_for_select(User.joins(:roles).where(roles: { id: 8}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    診察介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[10]{}", options_for_select(User.joins(:roles).where(roles: { id: 10}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    胸写
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[9]{}", options_for_select(User.joins(:roles).where(roles: { id: 9}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>

app/views/shifts/_typeC.html.erb
<div class="shift-detail">
  <div class="roll">
    問診
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[1]{}", options_for_select(User.joins(:roles).where(roles: { id: 1}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （6名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    採血
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[2]{}", options_for_select(User.joins(:roles).where(roles: { id: 2}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[13]{}", options_for_select(User.joins(:roles).where(roles: { id: 13}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    腹囲測定
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[4]{}", options_for_select(User.joins(:roles).where(roles: { id: 4}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    眼底
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[6]{}", options_for_select(User.joins(:roles).where(roles: { id: 6}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    診察介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[10]{}", options_for_select(User.joins(:roles).where(roles: { id: 10}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    胸写
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[9]{}", options_for_select(User.joins(:roles).where(roles: { id: 9}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    検尿
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[16]{}", options_for_select(User.joins(:roles).where(roles: { id: 16}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    セレクト
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[13]{}", options_for_select(User.joins(:roles).where(roles: { id: 13}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    がん問診
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[11]{}", options_for_select(User.joins(:roles).where(roles: { id: 11}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>

app/views/shifts/_typeD.html.erb
<div class="shift-detail">
  <div class="roll">
    心電図
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[14]{}", options_for_select(User.joins(:roles).where(roles: { id: 14}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    心電図介助
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[3]{}", options_for_select(User.joins(:roles).where(roles: { id: 3}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div> 
  </div>
  <div class="member">
    （4名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    採血
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[2]{}", options_for_select(User.joins(:roles).where(roles: { id: 2}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （8名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    ポータブル
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[17]{}", options_for_select(User.joins(:roles).where(roles: { id: 17}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （1名）
  </div>
</div>

app/views/shifts/_typeE.html.erb
<div class="shift-detail">
  <div class="roll">
    問診
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[1]{}", options_for_select(User.joins(:roles).where(roles: { id: 1}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （3名）
  </div>
</div>
<div class="shift-detail">
  <div class="roll">
    採血
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[2]{}", options_for_select(User.joins(:roles).where(roles: { id: 2}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （2名）
  </div>
</div>

app/views/shifts/_typeF.html.erb
<div class="shift-detail">
  <div class="roll">
    設営
  </div>
  <div class="custom-select">
    <div class="user-select">
      <%= f.select "user_role_combinations[18]{}", options_for_select(User.joins(:roles).where(roles: { id: 18}).order(id: :asc).map { |user| [user.name, user.id] }), {include_hidden: false}, {class: "user_id", multiple: true} %>
    </div>
  </div>
  <div class="member">
    （6名）
  </div>
</div>

app/views/shifts/index.html.erb
<% if user_signed_in? %>
  <%= month_calendar do |date| %>
    <%= date.day %>
  <% end %>

  <div class = "main-menu">
  <% if current_user.id == 1 %>
    <div class = "menu">
      <%= link_to 'スタッフ編集', roles_path, class:'edit-btn' %>
    </div>
    <div class = "menu"> 
      <%= link_to "シフト作成", new_shift_path, class: "shift-btn" %>
    </div>
  <% end %>
    <div class = "holiday-btm menu"> 
      勤務希望
    </div>
  </div>  
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '前の月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次の月'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>